#!/bin/bash
# This hook is run after this virtualenv is activated.
# This script is also used by Upstart in production

export DJANGO_SETTINGS_MODULE=lti_sandbox.settings.local
export DJANGO_DB_PASSWORD='changeme'
export CIPHER_KEY='changeme'
export DJANGO_SECRET_KEY='changeme'
